apiVersion: apps/v1
kind: Deployment
metadata:
  name: careconnect-api
  namespace: careconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careconnect-api
  template:
    metadata:
      labels:
        app: careconnect-api
    spec:
      containers:
        - name: careconnect-api
          image: laendletechregistry.azurecr.io/careconnect-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: JWT_SECRET
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "careconnect"
            - name: USE_MOCK
              value: "false"