version: '3'

services:
  db:
    image: postgres:latest
    container_name: careconnect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: careconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ../cc_api
    container_name: careconnect-api
    restart: always
    depends_on:
      - db
    environment:
      PORT: 4000
      JWT_SECRET: supersecretkey
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: careconnect
      USE_MOCK: "false"
    ports:
      - "4000:4000"

volumes:
  postgres_data: