apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: careconnect
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: careconnect
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk=  # base64 encoded "supersecretkey"