apiVersion: v1
kind: Service
metadata:
  name: careconnect-api
  namespace: careconnect
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000  # Anpassung an den tatsächlichen Container-Port
  selector:
    app: careconnect-api